config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:type_dish, :name, :description, :price)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :type_dish %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit dish</h1>

  <%= render 'form' %>
</div>

<div class="btn btn-link">
  <%= link_to 'Back', item_path %>
</div>

app/views/items/index.html.erb
<% @items.each do |item| %>
  <h2><%= link_to item.type_dish, item %></h2>
  <p><%= item.name %></p>
  <p><%= item.description %></p>
  <p><%= item.price %></p>
<% end %>

<div class="btn btn-link">
  <%= link_to 'new', new_item_path %>
</div>

app/views/items/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<div class="btn btn-link">
  <%= link_to 'Back', root_path %>
</div>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <h2><%= @item.type_dish %></h2>
  <p><%= @item.name %></p>
  <p><%= @item.description %></p>
  <p><%= @item.price %></p>


  <div class="col-md-4 col-md-offset-4">
    <%= link_to "Back", root_path %>
    <%= link_to "Edit", edit_item_path(@item) %>
    <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Restaurant", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
      </ul>
    </div>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in?  %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path  %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restorant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>